files:
  include: 'src/**/*.s+(a|c)ss'
  ignore: 
    - 'node_modules'
rules:
  # Color
  no-color-literals: 1
  hex-notation:
  - 1
  -
    style: lowercase

  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing (temp disabled not recognizing VS newlines)
  one-declaration-per-line: 0
  empty-line-between-blocks: 0
  single-line-per-selector: 0

  # Disallows
  no-misspelled-properties: 0
  shorthand-values: 0
  no-vendor-prefixes: 0
  no-mergeable-selectors: 0
  no-qualifying-elements: 0
  no-transition-all: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  no-debug: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-warn: 1
  no-css-comments: true
  no-duplicate-properties:
  - 0
  -
    exclude: [display, background]

  # Styles
  property-sort-order: 0
  clean-import-paths:
  - 0
  - 
    leading-underscore: true

  # disabling indentation because of VS issues but the rule applies
  indentation:
  - 1
  -
    size: 2

  leading-zero: 0
  nesting-depth:
  - 1
  -
    max-depth: 3
  
  quotes:
  - 1
  -
    style: single

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1

  # Disable temp
  final-newline: 0

  class-name-format:
    - 1
    -
      convention: hyphenatedbem