packages:
  - 'docs'
  - 'packages/components'
  - 'packages/crane'
  - 'packages/grid'
  - 'packages/icons'
  - 'packages/layout'
  - 'packages/test'
  - 'packages/themes'
  - 'packages/typography'
  - 'packages/typewriter'
  - 'examples/angular'
  - 'examples/react'
  - 'examples/vue'
