packages:
  - projects/docs
  - projects/components
  - projects/crane
  - projects/grid
  - projects/icons
  - projects/internals/eslint
  - projects/internals/test
  - projects/layout
  - projects/orbit
  - projects/themes
  - projects/typography
  - projects/typewriter
  - projects/virtual
  - projects/examples/angular
  - projects/examples/react
  - projects/examples/vue

catalog:
  '@blueprintui/cli': 0.12.0
  '@blueprintui/drafter': 0.10.0
  '@types/jasmine': 6.0.0
  '@web/dev-server': 0.4.6
  '@web/dev-server-esbuild': 1.0.4
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.20.2
  '@web/test-runner-core': 0.13.4
  '@web/test-runner-playwright': 0.11.1
  '@web/test-runner-visual-regression': 0.10.0
  browserslist: 4.25.4
  custom-element-types: 0.0.2
  del-cli: 6.0.0
  jasmine: 6.0.0
  jasmine-core: 6.0.1
  lit: ^3.3.1
  modern-normalize: ^3.0.1
  playwright: 1.58.0
  publint: 0.3.12
  tslib: ^2.8.1
  typescript: 6.0.0-beta
  vite: 8.0.0-beta.14
  web-test-runner-jasmine: 0.2.0
  web-test-runner-performance: 0.1.6

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@blueprintui/cli'
  - '@blueprintui/drafter'
  - playwright
  - playwright-core
  - web-test-runner-jasmine
managePackageManagerVersions: true
packageManagerStrictVersions: true
verifyDepsBeforeRun: install
