verifyDepsBeforeRun: install
managePackageManagerVersions: true
packageManagerStrictVersions: true
packages:
  - docs
  - packages/components
  - packages/crane
  - packages/grid
  - packages/icons
  - packages/layout
  - packages/test
  - packages/themes
  - packages/typography
  - packages/typewriter
  - examples/angular
  - examples/react
  - examples/vue
catalog:
  '@web/dev-server': 0.4.6
  '@web/dev-server-esbuild': 1.0.4
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.20.1
  '@web/test-runner-core': 0.13.4
  '@web/test-runner-playwright': 0.11.0
  '@web/test-runner-visual-regression': 0.10.0
  browserslist: 4.24.5
  custom-element-types: 0.0.2
  del-cli: 6.0.0
  lit: ^3.3.0
  tslib: ^2.8.1
  typescript: 5.8.3
  vite: 6.3.5
  modern-normalize: ^3.0.1
  playwright: 1.52.0
  publint: 0.3.12
  web-test-runner-jasmine: 0.1.2
  web-test-runner-performance: 0.1.6
onlyBuiltDependencies:
  - esbuild
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
