name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'
      - uses: google/wireit@setup-github-actions-caching/v2
      - run: npm run setup
      - run: npm run ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITES_FC2CF }}'
          channelId: live
          projectId: sites-fc2cf
          entryPoint: ./projects/docs
